import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'providers.dart';

class AppLocalization {
  final AppLanguage language;

  AppLocalization(this.language);

  static AppLocalization of(BuildContext context, WidgetRef ref) {
    final lang = ref.watch(languageProvider);
    return AppLocalization(lang);
  }

  static final Map<AppLanguage, Map<String, String>> _localizedValues = {
    AppLanguage.english: {
      'greeting': "श्री राधे",
      'home': "Home",
      'profile': "Profile",
      'discover_wisdom': "Vrinda Vaani",
      'search_hint': "Search shlokas, strotras...",
      'categories': "Categories",
      'see_all': "See All",
      'all': "All",
      'featured': "FEATURED",
      'featured_title': "Begin Your\nSpiritual Journey",
      'start_now': "Start Now",
      'recent_wisdom': "Recent Wisdom",
      'view_all': "View All",
      'settings': "Settings",
      'appearance': "Appearance",
      'dark_mode': "Dark Mode",
      'dark_mode_sub': "Enable immersive dark experience",
      'language': "Language",
      'notifications': "Notifications",
      'daily_wisdom': "Daily Wisdom",
      'daily_wisdom_sub': "Receive daily shlokas and inspirations",
      'account': "Account",
      'privacy_policy': "Privacy Policy",
      'terms_service': "Terms of Service",
      'delete_account': "Delete Account",
      'library': "My Library",
      'my_library': "My Library",
      'saved_items': "saved items",
      'reading_history': "Reading History",
      'about': "About Sant-Vaani",
      'logout': "Logout",
      'shlokas': "Shlokas",
      'strotras': "Strotras",
      'poems': "Poems",
      'vedas': "Vedas",
      'mantras': "Mantras",
      'stories': "Stories",
      'search': "Search",
      'find_wisdom': "Find sacred wisdom instantly",
      'popular_searches': "Popular Searches",
      'discover_wisdom_short': "Discover ancient wisdom",
      'no_results': "No results found",
      'results_found': "results found",
      'filter_sort': "Filter & Sort",
      'sort_by': "Sort By",
      'recent': "Recent",
      'popular': "Popular",
      'a_z': "A-Z",
      'clear_filters': "Clear Filters",
      'filter_options': "Filter Options",
      'no_content': "No content in",
      'sacred_texts': "sacred texts",
      'try_different': "Try a different search term",
      'check_back': "Check back later for new content",
      'publish_wisdom': "Publish Wisdom",
      'publish_success': "Sacred wisdom published successfully!",
      'add_wisdom': "Add New Wisdom",
      'title_label': "Title",
      'enter_title': "Enter the title of sacred text",
      'category_label': "Category",
      'sanskrit_label': "Sanskrit Content",
      'enter_sanskrit': "Enter Sanskrit verses",
      'english_label': "English Translation",
      'enter_english': "Enter English translation",
      'hindi_label': "Hindi Meaning",
      'enter_hindi': "Enter Hindi meaning",
      'commentary_label': "Commentary",
      'enter_commentary': "Add your commentary or explanation",
      'add_cover': "Tap to add cover image",
      'optional_limit': "Optional • PNG, JPG up to 5MB",
      'please_enter': "Please enter",
      'library_empty': "Your library is empty",
      'save_favorite': "Save your favorite sacred texts here",
      'explore_content': "Explore Content",
      'discover_wisdom_text': "Discover ancient wisdom",
      'sacred_text': "Sacred Text",
      'min_read': "min read",
      'languages': "languages",
      'english_translation': "ENGLISH TRANSLATION",
      'hindi_meaning': "HINDI MEANING",
      'commentary': "COMMENTARY",
      'added_library': "Added to Library",
      'removed_library': "Removed from Library",
      'playing_narration': "Playing narration...",
      'paused': "Paused",
      'pause': "Pause",
      'listen': "Listen",
      'admin_access': "Admin Access",
      'admin_access_sub': "Add and manage content",
    },
    AppLanguage.hindi: {
      'greeting': "श्री राधे 🙏",
      'home': "होम",
      'profile': "प्रोफाइल",
      'discover_wisdom': "ज्ञान की खोज करें",
      'search_hint': "श्लोक, स्तोत्र खोजें...",
      'categories': "श्रेणियाँ",
      'see_all': "सभी देखें",
      'all': "सभी",
      'featured': "विशेष",
      'featured_title': "अपनी आध्यात्मिक\nयात्रा शुरू करें",
      'start_now': "अभी शुरू करें",
      'recent_wisdom': "हालिया ज्ञान",
      'view_all': "सभी देखें",
      'settings': "सेटिंग्स",
      'appearance': "रूप-रंग",
      'dark_mode': "डार्क मोड",
      'dark_mode_sub': "गहरा अनुभव सक्षम करें",
      'language': "भाषा",
      'notifications': "सूचनाएं",
      'daily_wisdom': "दैनिक ज्ञान",
      'daily_wisdom_sub': "दैनिक श्लोक और प्रेरणा प्राप्त करें",
      'account': "खाता",
      'privacy_policy': "गोपनीयता नीति",
      'terms_service': "सेवा की शर्तें",
      'delete_account': "खाता हटाएं",
      'library': "मेरी लाइब्रेरी",
      'my_library': "मेरी लाइब्रेरी",
      'saved_items': "सहेजे गए आइटम",
      'reading_history': "पढ़ने का इतिहास",
      'about': "संत-वाणी के बारे में",
      'logout': "लॉगआउट",
      'shlokas': "श्लोक",
      'strotras': "स्तोत्र",
      'poems': "कविताएं",
      'vedas': "वेद",
      'mantras': "मंत्र",
      'stories': "कहानियाँ",
      'search': "खोजें",
      'find_wisdom': "तुरंत पवित्र ज्ञान खोजें",
      'popular_searches': "लोकप्रिय खोजें",
      'discover_wisdom_short': "प्राचीन ज्ञान की खोज करें",
      'no_results': "कोई परिणाम नहीं मिला",
      'results_found': "परिणाम मिले",
      'filter_sort': "फ़िल्टर और छँटाई",
      'sort_by': "इसके अनुसार क्रमबद्ध करें",
      'recent': "हालिया",
      'popular': "लोकप्रिय",
      'a_z': "A-Z",
      'clear_filters': "फ़िल्टर हटाएं",
      'filter_options': "फ़िल्टर विकल्प",
      'no_content': "में कोई सामग्री नहीं",
      'sacred_texts': "पवित्र ग्रंथ",
      'try_different': "एक अलग खोज शब्द आज़माएं",
      'check_back': "नई सामग्री के लिए बाद में देखें",
      'publish_wisdom': "ज्ञान प्रकाशित करें",
      'publish_success': "पवित्र ज्ञान सफलतापूर्वक प्रकाशित!",
      'add_wisdom': "नया ज्ञान जोड़ें",
      'title_label': "शीर्षक",
      'enter_title': "पवित्र पाठ का शीर्षक दर्ज करें",
      'category_label': "श्रेणी",
      'sanskrit_label': "संस्कृत सामग्री",
      'enter_sanskrit': "संस्कृत श्लोक दर्ज करें",
      'english_label': "अंग्रेजी अनुवाद",
      'enter_english': "अंग्रेजी अनुवाद दर्ज करें",
      'hindi_label': "हिंदी अर्थ",
      'enter_hindi': "हिंदी अर्थ दर्ज करें",
      'commentary_label': "टीका",
      'enter_commentary': "अपनी टीका या व्याख्या जोड़ें",
      'add_cover': "कवर इमेज जोड़ने के लिए टैप करें",
      'optional_limit': "वैकल्पिक • PNG, JPG 5MB तक",
      'please_enter': "कृपया दर्ज करें",
      'library_empty': "आपकी लाइब्रेरी खाली है",
      'save_favorite': "अपने पसंदीदा पवित्र ग्रंथ यहाँ सहेजें",
      'explore_content': "सामग्री देखें",
      'discover_wisdom_text': "प्राचीन ज्ञान की खोज करें",
      'sacred_text': "पवित्र पाठ",
      'min_read': "मिनट पढ़ें",
      'languages': "भाषाएं",
      'english_translation': "अंग्रेजी अनुवाद",
      'hindi_meaning': "हिंदी अर्थ",
      'commentary': "टीका",
      'added_library': "लाइब्रेरी में जोड़ा गया",
      'removed_library': "लाइब्रेरी से हटाया गया",
      'playing_narration': "वाचन चल रहा है...",
      'paused': "रोका गया",
      'pause': "रोकें",
      'listen': "सुनें",
      'admin_access': "एडमिन पहुंच",
      'admin_access_sub': "सामग्री जोड़ें और प्रबंधित करें",
    },
    AppLanguage.sanskrit: {
      'greeting': "नमो नमः 🙏",
      'home': "गृहम्",
      'profile': "परिचयः",
      'discover_wisdom': "ज्ञानं अन्वेषयतु",
      'search_hint': "श्लोकान्, स्तोत्राणि अन्वेषयतु...",
      'categories': "वर्गाः",
      'see_all': "सर्वे पश्यन्तु",
      'all': "सर्वे",
      'featured': "विशेषः",
      'featured_title': "भवतः आध्यात्मिक\nयात्रां आरभत",
      'start_now': "अधुनैव आरभत",
      'recent_wisdom': "अद्यतनं ज्ञानम्",
      'view_all': "सर्वे पश्यन्तु",
      'settings': "व्यवस्थापनम्",
      'appearance': "स्वरूपम्",
      'dark_mode': "कृष्णपक्षः",
      'dark_mode_sub': "कृष्णवर्णस्य अनुभूत्यै",
      'language': "भाषा",
      'notifications': "सूचनाः",
      'daily_wisdom': "दैनिकं ज्ञानम्",
      'daily_wisdom_sub': "प्रतिदिनं श्लोकान् प्रेरणां च प्राप्नुवन्तु",
      'account': "लेखः",
      'privacy_policy': "गोपनीयता नीतिः",
      'terms_service': "सेवा नियमाः",
      'delete_account': "लेखं विलोपयतु",
      'library': "मम पुस्तकालयः",
      'my_library': "मम पुस्तकालयः",
      'saved_items': "संगृहीताः विषयाः",
      'reading_history': "पठन इतिहासः",
      'about': "संत-वाणी विषयकम्",
      'logout': "बहिर्गमनम्",
      'shlokas': "श्लोकाः",
      'strotras': "स्तोत्राणि",
      'poems': "काव्यानि",
      'vedas': "वेदाः",
      'mantras': "मन्त्राः",
      'stories': "कथाः",
      'search': "अन्वेषणम्",
      'find_wisdom': "तत्कालमेव पवित्रज्ञानं अन्वेषयतु",
      'popular_searches': "लोकप्रियाणि अन्वेषणानि",
      'discover_wisdom_short': "प्राचीनज्ञानं अन्वेषयतु",
      'no_results': "किञ्चिदपि न प्राप्तम्",
      'results_found': "परिणामाः प्राप्ताः",
      'filter_sort': "शोधकः क्रमश्च",
      'sort_by': "क्रमेण स्थापयतु",
      'recent': "अद्यतनम्",
      'popular': "लोकप्रियम्",
      'a_z': "A-Z",
      'clear_filters': "शोधकान् निष्कासयतु",
      'filter_options': "शोधक विकल्पाः",
      'no_content': "विषयः नास्ति",
      'sacred_texts': "पवित्र ग्रन्थाः",
      'try_different': "अन्यं शब्दं अन्वेषयतु",
      'check_back': "नूतनविषयार्थं पुनः पश्यन्तु",
      'publish_wisdom': "ज्ञानं प्रकाशयतु",
      'publish_success': "पवित्रज्ञानं सफलतया प्रकाशितम्!",
      'add_wisdom': "नूतन ज्ञानं योजयतु",
      'title_label': "शीर्षकम्",
      'enter_title': "पवित्रपाठस्य शीर्षकं प्रविशतु",
      'category_label': "वर्गः",
      'sanskrit_label': "संस्कृत विषयः",
      'enter_sanskrit': "संस्कृत श्लोकान् प्रविशतु",
      'english_label': "आङ्ग्ल अनुवादः",
      'enter_english': "आङ्ग्लानुवादं प्रविशतु",
      'hindi_label': "हिन्दी अर्थः",
      'enter_hindi': "हिन्दी अर्थं प्रविशतु",
      'commentary_label': "भाष्यम्",
      'enter_commentary': "भवतः भाष्यं व्याख्यां वा योजयतु",
      'add_cover': "आवरणचित्रं योजयितुं स्पर्शं करोतु",
      'optional_limit': "वैकल्पिकम् • PNG, JPG 5MB पर्यन्तम्",
      'please_enter': "कृपया प्रविशतु",
      'library_empty': "भवतः पुस्तकालयः रिक्तः अस्ति",
      'save_favorite': "प्रियान् पवित्रग्रन्थान् अत्र संगृह्णातु",
      'explore_content': "विषयम् अन्वेषयतु",
      'discover_wisdom_text': "प्राचीनज्ञानं अन्वेषयतु",
      'sacred_text': "पवित्रपाठः",
      'min_read': "निमेषः पठनम्",
      'languages': "भाषाः",
      'english_translation': "आङ्ग्ल अनुवादः",
      'hindi_meaning': "हिन्दी अर्थः",
      'commentary': "भाष्यम्",
      'added_library': "पुस्तकालये योजितम्",
      'removed_library': "पुस्तकालयात् अपसारितम्",
      'playing_narration': "वाचनं प्रचलति...",
      'paused': "विरामितम्",
      'pause': "विरमतु",
      'listen': "शृणोतु",
      'admin_access': "प्रशासक प्रवेशः",
      'admin_access_sub': "विषयान् योजयतु प्रबन्धयतु च",
    },
  };

  String translate(String key) {
    return _localizedValues[language]?[key] ?? key;
  }
}
