-- Run this SQL in your Supabase SQL Editor to temporarily disable RLS for importing data
ALTER TABLE tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE places DISABLE ROW LEVEL SECURITY;
ALTER TABLE albums DISABLE ROW LEVEL SECURITY;
ALTER TABLE raags DISABLE ROW LEVEL SECURITY;
ALTER TABLE subjects DISABLE ROW LEVEL SECURITY;
ALTER TABLE glossarys DISABLE ROW LEVEL SECURITY;
ALTER TABLE medias DISABLE ROW LEVEL SECURITY;
ALTER TABLE article_tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE article_places DISABLE ROW LEVEL SECURITY;
ALTER TABLE article_raags DISABLE ROW LEVEL SECURITY;
ALTER TABLE article_subjects DISABLE ROW LEVEL SECURITY;
ALTER TABLE article_medias DISABLE ROW LEVEL SECURITY;
