-- Run this SQL in your Supabase SQL Editor to re-enable RLS after importing data
ALTER TABLE tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE places ENABLE ROW LEVEL SECURITY;
ALTER TABLE albums ENABLE ROW LEVEL SECURITY;
ALTER TABLE raags ENABLE ROW LEVEL SECURITY;
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE glossarys ENABLE ROW LEVEL SECURITY;
ALTER TABLE medias ENABLE ROW LEVEL SECURITY;
ALTER TABLE article_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE article_places ENABLE ROW LEVEL SECURITY;
ALTER TABLE article_raags ENABLE ROW LEVEL SECURITY;
ALTER TABLE article_subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE article_medias ENABLE ROW LEVEL SECURITY;
