// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU9VuBms1Ss8VzFEqFSWScQgwDTCDwPkw',
    appId: '1:1019370299171:android:421f8669d8a388dfcd3696',
    messagingSenderId: '1019370299171',
    projectId: 'login-me-vrinda',
    databaseURL: 'https://login-me-vrinda-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-me-vrinda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUKS4FEGc4UxBVdKqAg_ebye0wZMG2Xms',
    appId: '1:373857631114:ios:66d74abdd09886bfa82673',
    messagingSenderId: '373857631114',
    projectId: 'vrindavaanig',
    storageBucket: 'vrindavaanig.firebasestorage.app',
    iosBundleId: 'com.santvaani.santVaani',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxBytUXjMdhBQfSjjuaIGfcXZe8N0WkH0',
    appId: '1:1019370299171:web:1a6df319b2fbfd6fcd3696',
    messagingSenderId: '1019370299171',
    projectId: 'login-me-vrinda',
    authDomain: 'login-me-vrinda.firebaseapp.com',
    databaseURL: 'https://login-me-vrinda-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'login-me-vrinda.firebasestorage.app',
    measurementId: 'G-NN88X7N454',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUKS4FEGc4UxBVdKqAg_ebye0wZMG2Xms',
    appId: '1:373857631114:ios:66d74abdd09886bfa82673',
    messagingSenderId: '373857631114',
    projectId: 'vrindavaanig',
    storageBucket: 'vrindavaanig.firebasestorage.app',
    iosBundleId: 'com.santvaani.santVaani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4oSs_XYXyxAyOptMC8yTa1oscW9G16cY',
    appId: '1:373857631114:web:a836487499591a40a82673',
    messagingSenderId: '373857631114',
    projectId: 'vrindavaanig',
    authDomain: 'vrindavaanig.firebaseapp.com',
    storageBucket: 'vrindavaanig.firebasestorage.app',
    measurementId: 'G-7GBNBPC27X',
  );

}