// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgJ5hLlX6_yV3AJOL1u6zSy2G5FlNOc3s',
    appId: '1:373857631114:android:4651683427acc6caa82673',
    messagingSenderId: '373857631114',
    projectId: 'vrindavaanig',
    storageBucket: 'vrindavaanig.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUKS4FEGc4UxBVdKqAg_ebye0wZMG2Xms',
    appId: '1:373857631114:ios:66d74abdd09886bfa82673',
    messagingSenderId: '373857631114',
    projectId: 'vrindavaanig',
    storageBucket: 'vrindavaanig.firebasestorage.app',
    iosBundleId: 'com.santvaani.santVaani',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4oSs_XYXyxAyOptMC8yTa1oscW9G16cY',
    appId: '1:373857631114:web:f341d8a54711ca85a82673',
    messagingSenderId: '373857631114',
    projectId: 'vrindavaanig',
    authDomain: 'vrindavaanig.firebaseapp.com',
    storageBucket: 'vrindavaanig.firebasestorage.app',
    measurementId: 'G-YKQSX1MCDE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUKS4FEGc4UxBVdKqAg_ebye0wZMG2Xms',
    appId: '1:373857631114:ios:66d74abdd09886bfa82673',
    messagingSenderId: '373857631114',
    projectId: 'vrindavaanig',
    storageBucket: 'vrindavaanig.firebasestorage.app',
    iosBundleId: 'com.santvaani.santVaani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4oSs_XYXyxAyOptMC8yTa1oscW9G16cY',
    appId: '1:373857631114:web:a836487499591a40a82673',
    messagingSenderId: '373857631114',
    projectId: 'vrindavaanig',
    authDomain: 'vrindavaanig.firebaseapp.com',
    storageBucket: 'vrindavaanig.firebasestorage.app',
    measurementId: 'G-7GBNBPC27X',
  );

}