// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr78jEl1kzZ_MKRieUBlk5o5lO2p24vQU',
    appId: '1:1027361942428:android:c3a0b4ca14ae952753b659',
    messagingSenderId: '1027361942428',
    projectId: 'santvaanig',
    storageBucket: 'santvaanig.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_H5NWNm53LcmncHDiHZ9Xa2CqduQQIv4',
    appId: '1:1027361942428:ios:a6ce547a905c9a4553b659',
    messagingSenderId: '1027361942428',
    projectId: 'santvaanig',
    storageBucket: 'santvaanig.firebasestorage.app',
    androidClientId: '1027361942428-759e6auri7d4slameolhgs8q47mn1csu.apps.googleusercontent.com',
    iosClientId: '1027361942428-g0gisvdp87rpufeaij3d16mff3pv7d1d.apps.googleusercontent.com',
    iosBundleId: 'com.santvaani.santVaani',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV89ziohwoKmshLiZLxKm5JnbVPrYWL_o',
    appId: '1:1027361942428:web:c71feffde5f3567853b659',
    messagingSenderId: '1027361942428',
    projectId: 'santvaanig',
    authDomain: 'santvaanig.firebaseapp.com',
    storageBucket: 'santvaanig.firebasestorage.app',
    measurementId: 'G-Z4XX4EPYW3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_H5NWNm53LcmncHDiHZ9Xa2CqduQQIv4',
    appId: '1:1027361942428:ios:a6ce547a905c9a4553b659',
    messagingSenderId: '1027361942428',
    projectId: 'santvaanig',
    storageBucket: 'santvaanig.firebasestorage.app',
    androidClientId: '1027361942428-759e6auri7d4slameolhgs8q47mn1csu.apps.googleusercontent.com',
    iosClientId: '1027361942428-g0gisvdp87rpufeaij3d16mff3pv7d1d.apps.googleusercontent.com',
    iosBundleId: 'com.santvaani.santVaani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV89ziohwoKmshLiZLxKm5JnbVPrYWL_o',
    appId: '1:1027361942428:web:e1e7629135d4a64553b659',
    messagingSenderId: '1027361942428',
    projectId: 'santvaanig',
    authDomain: 'santvaanig.firebaseapp.com',
    storageBucket: 'santvaanig.firebasestorage.app',
    measurementId: 'G-T94PXCPVC4',
  );

}